# Generated by Django 4.2.27 on 2026-03-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when book was borrowed')),
                ('due_date', models.DateField(help_text='Date when book should be returned')),
                ('return_date', models.DateField(blank=True, help_text='Actual return date (null if not returned)', null=True)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='borrowed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('book', models.ForeignKey(help_text='Book being borrowed', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(help_text='Member borrowing the book', on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Borrow Record',
                'verbose_name_plural': 'Borrow Records',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
