# Generated by Django 4.2.27 on 2026-03-16 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(help_text='Unique member ID', max_length=20, unique=True)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('address', models.TextField(help_text='Residential address')),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('membership_date', models.DateField(auto_now_add=True, help_text='Date of membership registration')),
                ('is_active', models.BooleanField(default=True, help_text='Is membership active?')),
                ('user', models.OneToOneField(help_text='Link to user account', limit_choices_to={'user_type': 'member'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['member_id'],
            },
        ),
    ]
